### ISSUE TITLE
Add a search feature

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/leaderboard#5]
Add a textbox that allows searching for a particular username. After searching, only that username should show up. 
Bonus if all usernames with the search phrase in it show up as well.
A back button should be integreated as well to return to the home view.

**Comment by shreya-panale** [comment]
I will try doing this!

**Comment by srujandeshpande** [comment]
Awesome!

**Comment by abhishek-mishra17** [comment]
@srujandeshpande i would like to work on this

**Comment by anirudhRowjee** [comment]
I'm working on this too

**Comment by avinash-vk** [comment]
Guys apologies but i'm decreasing the bounty for this issue to 75 because as we all know its a fairly simple issue and not fair to other contributors, But we will make sure we give you appropriate extra bounty points depending on how aesthetic, responsive and functional your component looks and how much work you've done on it.
Thank you coders @abhishek-pes @ShreyaPanale  @anirudhRowjee
